name: build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest # macOS ARM64
            # - macos-latest-large # macOS x86_64 # disabled because we're poor
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - "5.2"
        include:
          - os: ubuntu-latest
            ocaml-version: "4.14"
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: setup
        run: |
          opam install . --deps-only --with-test --with-doc
      - name: build
        run: opam exec -- dune build @install
      - name: test
        run: opam exec -- dune runtest
