name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.2"
      - name: setup-deploy
        run: |
          opam install . --deps-only --with-test --with-doc
      - name: api
        run: |
          touch doc/.nojekyll
          opam exec - dune build @doc
          mv _build/default/_doc/_html doc/api
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/
          CLEAN: true
